// <auto-generated />
using System;
using AuctionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

//namespace AuctionService.Data.Migrations
//{
//    [DbContext(typeof(AuctionDbContext))]
//    [Migration("20231125211549_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.14")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("AuctionService.Entities.Auction", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<DateTime>("AuctionEnd")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("CurrentHighBid")
//                        .HasColumnType("int");

//                    b.Property<int>("ReservePrice")
//                        .HasColumnType("int");

//                    b.Property<string>("Seller")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("SoldAmount")
//                        .HasColumnType("int");

//                    b.Property<int>("Status")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Winner")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Auctions");
//                });

//            modelBuilder.Entity("AuctionService.Entities.Item", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid>("AuctionId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Color")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ImageUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Make")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Mileage")
//                        .HasColumnType("int");

//                    b.Property<string>("Model")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Year")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("AuctionId")
//                        .IsUnique();

//                    b.ToTable("Items");
//                });

//            modelBuilder.Entity("AuctionService.Entities.Item", b =>
//                {
//                    b.HasOne("AuctionService.Entities.Auction", "Auction")
//                        .WithOne("Item")
//                        .HasForeignKey("AuctionService.Entities.Item", "AuctionId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Auction");
//                });

//            modelBuilder.Entity("AuctionService.Entities.Auction", b =>
//                {
//                    b.Navigation("Item");
//                });
//#pragma warning restore 612, 618
//        //}
//    }
//}
